# 配置端口
server:
  port: 51104

spring:
  profiles:
    active: dev
#    active: sit
#    active: uat
#    active: pro

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    timeout: 5000

#  #  数据库配置
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/dome_shop?characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT+8
#    username: root
#    password: 5201128blue
